-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 13:06:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nemachtilkali
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nemachtilkali` ;

-- -----------------------------------------------------
-- Schema nemachtilkali
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nemachtilkali` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `nemachtilkali` ;

-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_catusers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_catusers` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_catusers` (
  `nmcu_id` INT NOT NULL AUTO_INCREMENT,
  `nmcu_desc` VARCHAR(100) NOT NULL DEFAULT '',
  `nmcu_createdate` DATETIME NOT NULL DEFAULT now(),
  `nmcu_moddate` DATETIME NULL,
  `nmcu_ucreate` INT NOT NULL DEFAULT 0,
  `nmcu_umod` INT NULL,
  `nmcu_status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`nmcu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_bunit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_bunit` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_bunit` (
  `nmbu_id` INT NOT NULL AUTO_INCREMENT,
  `nmbu_name` VARCHAR(200) NOT NULL DEFAULT '',
  `nmbu_ucreate` INT NOT NULL DEFAULT 0,
  `nmbu_createdate` DATETIME NOT NULL DEFAULT now(),
  `nmbu_umod` INT NULL,
  `nmbu_moddate` DATETIME NULL,
  `nmbu_status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`nmbu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_branchoffice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_branchoffice` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_branchoffice` (
  `nmbo_id` INT NOT NULL AUTO_INCREMENT,
  `nmbo_nombre` VARCHAR(200) NOT NULL DEFAULT '',
  `nmbo_calle` VARCHAR(100) NOT NULL DEFAULT '',
  `nmbo_next` VARCHAR(45) NOT NULL DEFAULT '',
  `nmbo_nint` VARCHAR(45) NOT NULL DEFAULT '',
  `nmbo_colonia` VARCHAR(100) NOT NULL DEFAULT '',
  `nmbo_mun` VARCHAR(100) NOT NULL DEFAULT '',
  `nmbo_estado` VARCHAR(100) NOT NULL DEFAULT '',
  `nmbo_telefono` VARCHAR(45) NOT NULL DEFAULT '',
  `nmbo_email` VARCHAR(100) NOT NULL DEFAULT '',
  `nmbo_cp` VARCHAR(20) NOT NULL DEFAULT '',
  `nmbo_ucreate` INT NOT NULL DEFAULT 0,
  `nmbo_createdate` DATETIME NOT NULL DEFAULT NOW(),
  `nmbo_umod` INT NULL,
  `nmbo_moddate` DATETIME NULL,
  `nmbo_status` INT NOT NULL DEFAULT 1,
  `nmbo_bu` INT NOT NULL,
  PRIMARY KEY (`nmbo_id`),
  INDEX `fk_nm_branchoffice_nm_bunit1_idx` (`nmbo_bu` ASC),
  CONSTRAINT `fk_nm_branchoffice_nm_bunit1`
    FOREIGN KEY (`nmbo_bu`)
    REFERENCES `nemachtilkali`.`nm_bunit` (`nmbu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_usuario` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_usuario` (
  `nmu_id` INT NOT NULL AUTO_INCREMENT,
  `nmu_uname` VARCHAR(45) NULL,
  `nmu_nombre` VARCHAR(100) NOT NULL DEFAULT '',
  `nmu_apaterno` VARCHAR(100) NOT NULL DEFAULT '',
  `nmu_materno` VARCHAR(100) NOT NULL DEFAULT '',
  `nmu_pass` VARCHAR(50) NOT NULL DEFAULT '',
  `nmu_email` VARCHAR(100) NOT NULL DEFAULT '',
  `nmu_createdate` DATETIME NOT NULL DEFAULT now(),
  `nmu_moddate` DATETIME NULL,
  `nmu_ucreate` INT NOT NULL DEFAULT 0,
  `nmu_umod` INT NULL,
  `nmu_status` INT NOT NULL DEFAULT 1,
  `nmu_catu` INT NOT NULL,
  `nmu_bo` INT NOT NULL,
  PRIMARY KEY (`nmu_id`),
  UNIQUE INDEX `nmu_uname_UNIQUE` (`nmu_uname` ASC),
  UNIQUE INDEX `nmu_email_UNIQUE` (`nmu_email` ASC),
  INDEX `fk_nm_usuario_nm_catusers_idx` (`nmu_catu` ASC),
  INDEX `fk_nm_usuario_nm_branchoffice1_idx` (`nmu_bo` ASC),
  CONSTRAINT `fk_nm_usuario_nm_catusers`
    FOREIGN KEY (`nmu_catu`)
    REFERENCES `nemachtilkali`.`nm_catusers` (`nmcu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nm_usuario_nm_branchoffice1`
    FOREIGN KEY (`nmu_bo`)
    REFERENCES `nemachtilkali`.`nm_branchoffice` (`nmbo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_clientes` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_clientes` (
  `nmcl_id` INT NOT NULL AUTO_INCREMENT,
  `nmcl_nombre` VARCHAR(100) NOT NULL DEFAULT '',
  `nmcl_apaterno` VARCHAR(100) NOT NULL DEFAULT '',
  `nmcl_amaterno` VARCHAR(100) NOT NULL DEFAULT '',
  `nmcl_mtel` VARCHAR(45) NOT NULL DEFAULT '',
  `nmcl_ftel` VARCHAR(45) NOT NULL DEFAULT '',
  `nmcl_status` INT NOT NULL DEFAULT 1,
  `nmcl_createdate` DATETIME NOT NULL DEFAULT now(),
  `nmcl_moddate` DATETIME NULL,
  `nmcl_ucreate` INT NOT NULL,
  PRIMARY KEY (`nmcl_id`),
  INDEX `fk_nm_clientes_nm_usuario1_idx` (`nmcl_ucreate` ASC),
  CONSTRAINT `fk_nm_clientes_nm_usuario1`
    FOREIGN KEY (`nmcl_ucreate`)
    REFERENCES `nemachtilkali`.`nm_usuario` (`nmu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_catmembership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_catmembership` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_catmembership` (
  `nmcm_id` INT NOT NULL AUTO_INCREMENT,
  `nmcm_desc` VARCHAR(200) NOT NULL DEFAULT '',
  `nmcm_status` INT NOT NULL DEFAULT 1,
  `nmcm_createdate` DATETIME NOT NULL DEFAULT now(),
  `nmcm_moddate` DATETIME NULL,
  `nmcm_ucreate` INT NOT NULL DEFAULT 0,
  `nmcm_umod` INT NULL,
  PRIMARY KEY (`nmcm_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_dclientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_dclientes` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_dclientes` (
  `nmcld_id` INT NOT NULL AUTO_INCREMENT,
  `nmcld_calle` VARCHAR(100) NOT NULL DEFAULT '',
  `nmcld_next` VARCHAR(45) NOT NULL DEFAULT '',
  `nmcld_nint` VARCHAR(45) NOT NULL DEFAULT '',
  `nmcld_colonia` VARCHAR(100) NOT NULL DEFAULT '',
  `nmcld_mun` VARCHAR(100) NOT NULL DEFAULT '',
  `nmcld_cp` VARCHAR(20) NOT NULL DEFAULT '',
  `nmcld_cid` INT NOT NULL,
  PRIMARY KEY (`nmcld_id`),
  INDEX `fk_nm_dclientes_nm_clientes1_idx` (`nmcld_cid` ASC),
  CONSTRAINT `fk_nm_dclientes_nm_clientes1`
    FOREIGN KEY (`nmcld_cid`)
    REFERENCES `nemachtilkali`.`nm_clientes` (`nmcl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_catclases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_catclases` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_catclases` (
  `nmcclas_id` INT NOT NULL AUTO_INCREMENT,
  `nmcclas_desc` VARCHAR(200) NOT NULL DEFAULT '',
  `nmcclas_ucreate` INT NOT NULL DEFAULT 0,
  `nmcclas_createdate` DATETIME NOT NULL DEFAULT NOW(),
  `nmcclas_umod` INT NULL,
  `nmcclas_moddate` DATETIME NULL,
  `nmcclas_status` INT NOT NULL DEFAULT 1,
  `nmclas_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`nmcclas_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_cathorarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_cathorarios` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_cathorarios` (
  `nmch_id` INT NOT NULL AUTO_INCREMENT,
  `nmch_hinicio` VARCHAR(20) NOT NULL DEFAULT '',
  `nmch_hfinal` VARCHAR(20) NOT NULL DEFAULT '',
  `nmch_dia` VARCHAR(45) NOT NULL DEFAULT '',
  `nmch_ucreate` INT NOT NULL DEFAULT 0,
  `nmch_createdate` DATETIME NOT NULL DEFAULT now(),
  `nmch_umod` INT NULL,
  `nmch_moddate` DATETIME NULL,
  `nmch_status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`nmch_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_lista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_lista` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_lista` (
  `nml_id` INT NOT NULL AUTO_INCREMENT,
  `nml_createdate` DATETIME NOT NULL DEFAULT now(),
  `nml_cid` INT NOT NULL,
  `nml_uid` INT NOT NULL,
  PRIMARY KEY (`nml_id`),
  INDEX `fk_nm_lista_nm_clientes1_idx` (`nml_cid` ASC),
  INDEX `fk_nm_lista_nm_usuario1_idx` (`nml_uid` ASC),
  CONSTRAINT `fk_nm_lista_nm_clientes1`
    FOREIGN KEY (`nml_cid`)
    REFERENCES `nemachtilkali`.`nm_clientes` (`nmcl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nm_lista_nm_usuario1`
    FOREIGN KEY (`nml_uid`)
    REFERENCES `nemachtilkali`.`nm_usuario` (`nmu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_dlista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_dlista` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_dlista` (
  `nmdl_id` INT NOT NULL AUTO_INCREMENT,
  `nmdl_lid` INT NOT NULL,
  `nmdl_cclas` INT NOT NULL,
  `nmdl_chorario` INT NOT NULL,
  PRIMARY KEY (`nmdl_id`),
  INDEX `fk_nm_dlista_nm_lista1_idx` (`nmdl_lid` ASC),
  INDEX `fk_nm_dlista_nm_catclases1_idx` (`nmdl_cclas` ASC),
  INDEX `fk_nm_dlista_nm_cathorarios1_idx` (`nmdl_chorario` ASC),
  CONSTRAINT `fk_nm_dlista_nm_lista1`
    FOREIGN KEY (`nmdl_lid`)
    REFERENCES `nemachtilkali`.`nm_lista` (`nml_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nm_dlista_nm_catclases1`
    FOREIGN KEY (`nmdl_cclas`)
    REFERENCES `nemachtilkali`.`nm_catclases` (`nmcclas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nm_dlista_nm_cathorarios1`
    FOREIGN KEY (`nmdl_chorario`)
    REFERENCES `nemachtilkali`.`nm_cathorarios` (`nmch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_pagos` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_pagos` (
  `nmp_id` INT NOT NULL AUTO_INCREMENT,
  `nmp_memdates` DATETIME NOT NULL DEFAULT now(),
  `nmp_memdatef` DATETIME NULL,
  `nmp_memtype` INT NOT NULL,
  `nmp_client` INT NOT NULL,
  `nmp_urecivepay` INT NOT NULL,
  `nmp_memstatus` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`nmp_id`),
  INDEX `fk_nm_pagos_nm_catmembership1_idx` (`nmp_memtype` ASC),
  INDEX `fk_nm_pagos_nm_clientes1_idx` (`nmp_client` ASC),
  INDEX `fk_nm_pagos_nm_usuario1_idx` (`nmp_urecivepay` ASC),
  CONSTRAINT `fk_nm_pagos_nm_catmembership1`
    FOREIGN KEY (`nmp_memtype`)
    REFERENCES `nemachtilkali`.`nm_catmembership` (`nmcm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nm_pagos_nm_clientes1`
    FOREIGN KEY (`nmp_client`)
    REFERENCES `nemachtilkali`.`nm_clientes` (`nmcl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nm_pagos_nm_usuario1`
    FOREIGN KEY (`nmp_urecivepay`)
    REFERENCES `nemachtilkali`.`nm_usuario` (`nmu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_catpagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_catpagos` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_catpagos` (
  `nmcp_id` INT NOT NULL AUTO_INCREMENT,
  `nmcp_desc` VARCHAR(100) NOT NULL DEFAULT '',
  `nmcp_createdate` DATETIME NOT NULL DEFAULT now(),
  `nmcp_ucreate` INT NOT NULL DEFAULT 0,
  `nmcp_moddate` DATETIME NULL,
  `nmcp_umod` INT NULL,
  `nmcp_status` INT NOT NULL DEFAULT 1,
  `nmcp_amount` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`nmcp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_dpagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_dpagos` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_dpagos` (
  `nmdp_id` INT NOT NULL AUTO_INCREMENT,
  `nmdp_mpayment` DATETIME NOT NULL DEFAULT now(),
  `nmdp_pid` INT NOT NULL,
  `nmdp_payid` INT NOT NULL,
  `nmdp_status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`nmdp_id`),
  INDEX `fk_nm_dpagos_nm_pagos1_idx` (`nmdp_pid` ASC),
  INDEX `fk_nm_dpagos_nm_catpagos1_idx` (`nmdp_payid` ASC),
  CONSTRAINT `fk_nm_dpagos_nm_pagos1`
    FOREIGN KEY (`nmdp_pid`)
    REFERENCES `nemachtilkali`.`nm_pagos` (`nmp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nm_dpagos_nm_catpagos1`
    FOREIGN KEY (`nmdp_payid`)
    REFERENCES `nemachtilkali`.`nm_catpagos` (`nmcp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_config` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_config` (
  `nmconf_id` INT NOT NULL AUTO_INCREMENT,
  `nmconf_value` VARCHAR(250) NOT NULL DEFAULT '',
  `nmconf_status` INT NOT NULL DEFAULT 1,
  `nmconf_createdate` DATETIME NOT NULL DEFAULT now(),
  `nmconf_ucreate` INT NOT NULL DEFAULT 0,
  `nmconf_moddate` DATETIME NULL,
  `nmconf_umod` INT NULL,
  PRIMARY KEY (`nmconf_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nemachtilkali`.`nm_usess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nemachtilkali`.`nm_usess` ;

CREATE TABLE IF NOT EXISTS `nemachtilkali`.`nm_usess` (
  `nmus_id` INT NOT NULL AUTO_INCREMENT,
  `nmus_token` VARCHAR(45) NOT NULL DEFAULT '',
  `nmus_createdate` DATETIME NOT NULL DEFAULT now(),
  `nmus_status` INT NOT NULL DEFAULT 1,
  `nmus_userid` INT NOT NULL,
  PRIMARY KEY (`nmus_id`),
  INDEX `fk_nm_usess_nm_usuario1_idx` (`nmus_userid` ASC),
  CONSTRAINT `fk_nm_usess_nm_usuario1`
    FOREIGN KEY (`nmus_userid`)
    REFERENCES `nemachtilkali`.`nm_usuario` (`nmu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
